#!/bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [[ "$current_branch" == "main" ]]; then
  echo "Error: Committing to 'main' is not allowed. Please switch to a feature or a bug branch."
  exit 1
fi

pnpm exec lint-staged
