#!/bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [[ "$current_branch" == "main" ]]; then
  echo "Error: Pushing directly to 'main' is not allowed. Please push to a feature or a bug branch."
  exit 1
fi

pnpm run lint
